import { Injectable } from "@nestjs/common";

@Injectable()
export class NestjsCurrencyInfoByCountryNameService {
	private countryCurrencyMap: { [key: string]: { name: string; code: string; symbol: string } } = {
		Afghanistan: { name: "Afghan Afghani", code: "AFN", symbol: "؋" },
		Albania: { name: "Albanian Lek", code: "ALL", symbol: "Lek" },
		Algeria: { name: "Algerian Dinar", code: "DZD", symbol: "د.ج" },
		Andorra: { name: "Euro", code: "EUR", symbol: "€" },
		Angola: { name: "Angolan Kwanza", code: "AOA", symbol: "Kz" },
		"Antigua and Barbuda": { name: "East Caribbean Dollar", code: "XCD", symbol: "$" },
		Argentina: { name: "Argentine Peso", code: "ARS", symbol: "$" },
		Armenia: { name: "Armenian Dram", code: "AMD", symbol: "֏" },
		Australia: { name: "Australian Dollar", code: "AUD", symbol: "$" },
		Austria: { name: "Euro", code: "EUR", symbol: "€" },
		Azerbaijan: { name: "Azerbaijani Manat", code: "AZN", symbol: "₼" },
		Bahamas: { name: "Bahamian Dollar", code: "BSD", symbol: "$" },
		Bahrain: { name: "Bahraini Dinar", code: "BHD", symbol: "د.ب" },
		Bangladesh: { name: "Bangladeshi Taka", code: "BDT", symbol: "৳" },
		Barbados: { name: "Barbadian Dollar", code: "BBD", symbol: "$" },
		Belarus: { name: "Belarusian Ruble", code: "BYN", symbol: "Br" },
		Belgium: { name: "Euro", code: "EUR", symbol: "€" },
		Belize: { name: "Belize Dollar", code: "BZD", symbol: "$" },
		Benin: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
		Bhutan: { name: "Bhutanese Ngultrum", code: "BTN", symbol: "Nu." },
		Bolivia: { name: "Bolivian Boliviano", code: "BOB", symbol: "Bs" },
		"Bosnia and Herzegovina": { name: "Bosnia and Herzegovina Convertible Mark", code: "BAM", symbol: "KM" },
		Botswana: { name: "Botswana Pula", code: "BWP", symbol: "P" },
		Brazil: { name: "Brazilian Real", code: "BRL", symbol: "R$" },
		Brunei: { name: "Brunei Dollar", code: "BND", symbol: "$" },
		Bulgaria: { name: "Bulgarian Lev", code: "BGN", symbol: "лв" },
		"Burkina Faso": { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
		Burundi: { name: "Burundian Franc", code: "BIF", symbol: "Fr" },
		"Cabo Verde": { name: "Cape Verdean Escudo", code: "CVE", symbol: "$" },
		Cambodia: { name: "Cambodian Riel", code: "KHR", symbol: "៛" },
		Cameroon: { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
		Canada: { name: "Canadian Dollar", code: "CAD", symbol: "$" },
		"Central African Republic": { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
		Chad: { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
		Chile: { name: "Chilean Peso", code: "CLP", symbol: "$" },
		China: { name: "Chinese Yuan", code: "CNY", symbol: "¥" },
		Colombia: { name: "Colombian Peso", code: "COP", symbol: "$" },
		Comoros: { name: "Comorian Franc", code: "KMF", symbol: "Fr" },
		Congo: { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
		"Congo, Democratic Republic of the": { name: "Congolese Franc", code: "CDF", symbol: "Fr" },
		"Costa Rica": { name: "Costa Rican Colón", code: "CRC", symbol: "₡" },
		Croatia: { name: "Croatian Kuna", code: "HRK", symbol: "kn" },
		Cuba: { name: "Cuban Peso", code: "CUP", symbol: "₱" },
		Cyprus: { name: "Euro", code: "EUR", symbol: "€" },
		"Czech Republic": { name: "Czech Koruna", code: "CZK", symbol: "Kč" },
		Denmark: { name: "Danish Krone", code: "DKK", symbol: "kr" },
		Djibouti: { name: "Djiboutian Franc", code: "DJF", symbol: "Fr" },
		Dominica: { name: "East Caribbean Dollar", code: "XCD", symbol: "$" },
		"Dominican Republic": { name: "Dominican Peso", code: "DOP", symbol: "RD$" },
		"East Timor": { name: "United States Dollar", code: "USD", symbol: "$" },
		Ecuador: { name: "United States Dollar", code: "USD", symbol: "$" },
		Egypt: { name: "Egyptian Pound", code: "EGP", symbol: "ج.م" },
		"El Salvador": { name: "United States Dollar", code: "USD", symbol: "$" },
		"Equatorial Guinea": { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
		Eritrea: { name: "Eritrean Nakfa", code: "ERN", symbol: "Nfk" },
		Estonia: { name: "Euro", code: "EUR", symbol: "€" },
		Eswatini: { name: "Swazi Lilangeni", code: "SZL", symbol: "E" },
		Ethiopia: { name: "Ethiopian Birr", code: "ETB", symbol: "Br" },
		Fiji: { name: "Fijian Dollar", code: "FJD", symbol: "$" },
		Finland: { name: "Euro", code: "EUR", symbol: "€" },
		France: { name: "Euro", code: "EUR", symbol: "€" },
		Gabon: { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
		Gambia: { name: "Gambian Dalasi", code: "GMD", symbol: "D" },
		Georgia: { name: "Georgian Lari", code: "GEL", symbol: "₾" },
		Germany: { name: "Euro", code: "EUR", symbol: "€" },
		Ghana: { name: "Ghanaian Cedi", code: "GHS", symbol: "₵" },
		Greece: { name: "Euro", code: "EUR", symbol: "€" },
		Grenada: { name: "East Caribbean Dollar", code: "XCD", symbol: "$" },
		Guatemala: { name: "Guatemalan Quetzal", code: "GTQ", symbol: "Q" },
		Guinea: { name: "Guinean Franc", code: "GNF", symbol: "Fr" },
		"Guinea-Bissau": { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
		Guyana: { name: "Guyanese Dollar", code: "GYD", symbol: "$" },
		Haiti: { name: "Haitian Gourde", code: "HTG", symbol: "G" },
		Honduras: { name: "Honduran Lempira", code: "HNL", symbol: "L" },
		Hungary: { name: "Hungarian Forint", code: "HUF", symbol: "Ft" },
		Iceland: { name: "Icelandic Króna", code: "ISK", symbol: "kr" },
		India: { name: "Indian Rupee", code: "INR", symbol: "₹" },
		Indonesia: { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp" },
		Iran: { name: "Iranian Rial", code: "IRR", symbol: "﷼" },
		Iraq: { name: "Iraqi Dinar", code: "IQD", symbol: "ع.د" },
		Ireland: { name: "Euro", code: "EUR", symbol: "€" },
		Israel: { name: "Israeli New Shekel", code: "ILS", symbol: "₪" },
		Italy: { name: "Euro", code: "EUR", symbol: "€" },
		Jamaica: { name: "Jamaican Dollar", code: "JMD", symbol: "$" },
		Japan: { name: "Japanese Yen", code: "JPY", symbol: "¥" },
		Jordan: { name: "Jordanian Dinar", code: "JOD", symbol: "د.ا" },
		Kazakhstan: { name: "Kazakhstani Tenge", code: "KZT", symbol: "₸" },
		Kenya: { name: "Kenyan Shilling", code: "KES", symbol: "KSh" },
		Kiribati: { name: "Australian Dollar", code: "AUD", symbol: "$" },
		"Korea, North": { name: "North Korean Won", code: "KPW", symbol: "₩" },
		"Korea, South": { name: "South Korean Won", code: "KRW", symbol: "₩" },
		Kuwait: { name: "Kuwaiti Dinar", code: "KWD", symbol: "د.ك" },
		Kyrgyzstan: { name: "Kyrgystani Som", code: "KGS", symbol: "лв" },
		Laos: { name: "Lao Kip", code: "LAK", symbol: "₭" },
		Latvia: { name: "Euro", code: "EUR", symbol: "€" },
		Lebanon: { name: "Lebanese Pound", code: "LBP", symbol: "ل.ل" },
		Lesotho: { name: "Lesotho Loti", code: "LSL", symbol: "L" },
		Liberia: { name: "Liberian Dollar", code: "LRD", symbol: "$" },
		Libya: { name: "Libyan Dinar", code: "LYD", symbol: "د.ل" },
		Liechtenstein: { name: "Swiss Franc", code: "CHF", symbol: "CHF" },
		Lithuania: { name: "Euro", code: "EUR", symbol: "€" },
		Luxembourg: { name: "Euro", code: "EUR", symbol: "€" },
		Madagascar: { name: "Malagasy Ariary", code: "MGA", symbol: "Ar" },
		Malawi: { name: "Malawian Kwacha", code: "MWK", symbol: "K" },
		Malaysia: { name: "Malaysian Ringgit", code: "MYR", symbol: "RM" },
		Malta: { name: "Euro", code: "EUR", symbol: "€" },
		"Marshall Islands": { name: "United States Dollar", code: "USD", symbol: "$" },
		Mauritania: { name: "Mauritanian Ouguiya", code: "MRU", symbol: "UM" },
		Mauritius: { name: "Mauritian Rupee", code: "MUR", symbol: "₨" },
		Mexico: { name: "Mexican Peso", code: "MXN", symbol: "$" },
		Micronesia: { name: "United States Dollar", code: "USD", symbol: "$" },
		Moldova: { name: "Moldovan Leu", code: "MDL", symbol: "Leu" },
		Monaco: { name: "Euro", code: "EUR", symbol: "€" },
		Mongolia: { name: "Mongolian Tugrik", code: "MNT", symbol: "₮" },
		Montenegro: { name: "Euro", code: "EUR", symbol: "€" },
		Morocco: { name: "Moroccan Dirham", code: "MAD", symbol: "د.م." },
		Mozambique: { name: "Mozambican Metical", code: "MZN", symbol: "MT" },
		Myanmar: { name: "Burmese Kyat", code: "MMK", symbol: "Ks" },
		Namibia: { name: "Namibian Dollar", code: "NAD", symbol: "$" },
		Nauru: { name: "Australian Dollar", code: "AUD", symbol: "$" },
		Nepal: { name: "Nepalese Rupee", code: "NPR", symbol: "₨" },
		Netherlands: { name: "Euro", code: "EUR", symbol: "€" },
		"New Zealand": { name: "New Zealand Dollar", code: "NZD", symbol: "$" },
		Nicaragua: { name: "Nicaraguan Córdoba", code: "NIO", symbol: "C$" },
		Niger: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
		Nigeria: { name: "Naira", code: "NGN", symbol: "₦" },
		"North Macedonia": { name: "Macedonian Denar", code: "MKD", symbol: "ден" },
		Norway: { name: "Norwegian Krone", code: "NOK", symbol: "kr" },
		Oman: { name: "Omani Rial", code: "OMR", symbol: "ر.ع." },
		Pakistan: { name: "Pakistani Rupee", code: "PKR", symbol: "Rs" },
		Palau: { name: "United States Dollar", code: "USD", symbol: "$" },
		Panama: { name: "Panamanian Balboa", code: "PAB", symbol: "B/." },
		"Papua New Guinea": { name: "Papua New Guinean Kina", code: "PGK", symbol: "K" },
		Paraguay: { name: "Paraguayan Guarani", code: "PYG", symbol: "₲" },
		Peru: { name: "Peruvian Sol", code: "PEN", symbol: "S/" },
		Philippines: { name: "Philippine Peso", code: "PHP", symbol: "₱" },
		Poland: { name: "Polish Zloty", code: "PLN", symbol: "zł" },
		Portugal: { name: "Euro", code: "EUR", symbol: "€" },
		Qatar: { name: "Qatari Riyal", code: "QAR", symbol: "ر.ق" },
		Romania: { name: "Romanian Leu", code: "RON", symbol: "lei" },
		Russia: { name: "Russian Ruble", code: "RUB", symbol: "₽" },
		Rwanda: { name: "Rwandan Franc", code: "RWF", symbol: "Fr" },
		"Saint Kitts and Nevis": { name: "East Caribbean Dollar", code: "XCD", symbol: "$" },
		"Saint Lucia": { name: "East Caribbean Dollar", code: "XCD", symbol: "$" },
		"Saint Vincent and the Grenadines": { name: "East Caribbean Dollar", code: "XCD", symbol: "$" },
		Samoa: { name: "Samoan Tala", code: "WST", symbol: "T" },
		"San Marino": { name: "Euro", code: "EUR", symbol: "€" },
		"Sao Tome and Principe": { name: "Sao Tome and Principe Dobra", code: "STN", symbol: "Db" },
		"Saudi Arabia": { name: "Saudi Riyal", code: "SAR", symbol: "ر.س" },
		Senegal: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
		Serbia: { name: "Serbian Dinar", code: "RSD", symbol: "дин." },
		Seychelles: { name: "Seychellois Rupee", code: "SCR", symbol: "₨" },
		"Sierra Leone": { name: "Sierra Leonean Leone", code: "SLL", symbol: "Le" },
		Singapore: { name: "Singapore Dollar", code: "SGD", symbol: "$" },
		Slovakia: { name: "Euro", code: "EUR", symbol: "€" },
		Slovenia: { name: "Euro", code: "EUR", symbol: "€" },
		"Solomon Islands": { name: "Solomon Islands Dollar", code: "SBD", symbol: "$" },
		Somalia: { name: "Somali Shilling", code: "SOS", symbol: "Sh" },
		"South Africa": { name: "South African Rand", code: "ZAR", symbol: "R" },
		"South Sudan": { name: "South Sudanese Pound", code: "SSP", symbol: "£" },
		Spain: { name: "Euro", code: "EUR", symbol: "€" },
		"Sri Lanka": { name: "Sri Lankan Rupee", code: "LKR", symbol: "Rs" },
		Sudan: { name: "Sudanese Pound", code: "SDG", symbol: "ج.س" },
		Suriname: { name: "Surinamese Dollar", code: "SRD", symbol: "$" },
		Sweden: { name: "Swedish Krona", code: "SEK", symbol: "kr" },
		Switzerland: { name: "Swiss Franc", code: "CHF", symbol: "CHF" },
		Syria: { name: "Syrian Pound", code: "SYP", symbol: "ل.س" },
		Taiwan: { name: "New Taiwan Dollar", code: "TWD", symbol: "NT$" },
		Tajikistan: { name: "Tajikistani Somoni", code: "TJS", symbol: "SM" },
		Tanzania: { name: "Tanzanian Shilling", code: "TZS", symbol: "TSh" },
		Thailand: { name: "Thai Baht", code: "THB", symbol: "฿" },
		Togo: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
		Tonga: { name: "Tongan Paʻanga", code: "TOP", symbol: "T$" },
		"Trinidad and Tobago": { name: "Trinidad and Tobago Dollar", code: "TTD", symbol: "$" },
		Tunisia: { name: "Tunisian Dinar", code: "TND", symbol: "د.ت" },
		Turkey: { name: "Turkish Lira", code: "TRY", symbol: "₺" },
		Turkmenistan: { name: "Turkmenistani Manat", code: "TMT", symbol: "T" },
		Tuvalu: { name: "Australian Dollar", code: "AUD", symbol: "$" },
		Uganda: { name: "Ugandan Shilling", code: "UGX", symbol: "USh" },
		Ukraine: { name: "Ukrainian Hryvnia", code: "UAH", symbol: "₴" },
		"United Arab Emirates": { name: "United Arab Emirates Dirham", code: "AED", symbol: "د.إ" },
		"United Kingdom": { name: "Pound Sterling", code: "GBP", symbol: "£" },
		"United States": { name: "United States Dollar", code: "USD", symbol: "$" },
		Uruguay: { name: "Uruguayan Peso", code: "UYU", symbol: "$" },
		Uzbekistan: { name: "Uzbekistani Som", code: "UZS", symbol: "лв" },
		Vanuatu: { name: "Vanuatu Vatu", code: "VUV", symbol: "Vt" },
		"Vatican City": { name: "Euro", code: "EUR", symbol: "€" },
		Venezuela: { name: "Venezuelan Bolívar", code: "VES", symbol: "Bs" },
		Vietnam: { name: "Vietnamese Dong", code: "VND", symbol: "₫" },
		Yemen: { name: "Yemeni Rial", code: "YER", symbol: "ر.ي" },
		Zambia: { name: "Zambian Kwacha", code: "ZMW", symbol: "ZK" },
		Zimbabwe: { name: "Zimbabwean Dollar", code: "ZWL", symbol: "$" },
	};

	getCurrencyInfo(countryName: string): { name: string; code: string; symbol: string } | null {
		const currencyInfo = this.countryCurrencyMap[countryName];
		return currencyInfo ? currencyInfo : null;
	}
}
